name: Validate committed file names in tasks/

on:
  push:
    branches:
      - main

jobs:
  validate-task-files:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Validate committed file names in tasks/
        run: |
          git diff --name-only HEAD^ HEAD tasks/[0-9]+ | for file in $(cat); do
            echo "$file"
            if ! [[ $file =~ ^task_[0-9]+_solutions\.py$ ]]; then
              echo "Invalid file name: $file"
              exit 1
            fi
          done